import type { Parking } from '@/types';
import { DEMO_DESTINATION } from './destination';

/**
 * 12 parcheggi sintetici attorno alla destinazione demo.
 * Nomi chiaramente fittizi. Ogni voce è marcata isDemo: true.
 * I casi coprono: economico/distante, costoso/vicino, compromesso, coperto/scoperto,
 * con/senza EV, fuori/vicino ZTL, dati affidabili/poco affidabili, incompatibile van,
 * H24 e orario limitato.
 */

const { latitude: dLat, longitude: dLng } = DEMO_DESTINATION.coordinates;

/** piccolo offset in gradi per posizionare i parcheggi attorno alla destinazione */
function offset(mLat: number, mLng: number): { latitude: number; longitude: number } {
  return { latitude: dLat + mLat / 111_000, longitude: dLng + mLng / 78_000 };
}

export const DEMO_PARKINGS: Parking[] = [
  {
    id: 'demo-centro-uno',
    name: 'Parqo Centro Uno',
    slug: 'parqo-centro-uno',
    description: 'Autorimessa coperta nel cuore della città, ideale per soste brevi.',
    address: 'Via del Centro 1',
    city: 'Città Demo',
    ...offset(140, 90),
    pricePerHour: 3.5,
    dailyMaxPrice: 28,
    estimatedTotalPrice: 10.5,
    currency: 'EUR',
    walkingDistanceMeters: 180,
    walkingDurationMinutes: 3,
    drivingDurationMinutes: 12,
    totalDurationMinutes: 15,
    isCovered: true,
    isBookable: true,
    hasEvCharging: true,
    isAccessible: true,
    isOpen24Hours: true,
    isOutsideZtl: false,
    maxVehicleHeightCm: 200,
    totalSpaces: 320,
    dataConfidence: 'high',
    dataSource: 'demo',
    lastVerifiedAt: '2026-07-10T09:00:00Z',
    tags: ['Coperto', 'Prenotabile', 'EV', 'Accessibile', 'H24'],
    isDemo: true,
  },
  {
    id: 'demo-stazione',
    name: 'Parqo Stazione',
    slug: 'parqo-stazione',
    description: 'Ampio parcheggio vicino alla stazione, ottimo rapporto qualità-prezzo.',
    address: 'Piazzale della Stazione 4',
    city: 'Città Demo',
    ...offset(-620, 480),
    pricePerHour: 2,
    dailyMaxPrice: 16,
    estimatedTotalPrice: 6,
    currency: 'EUR',
    walkingDistanceMeters: 780,
    walkingDurationMinutes: 10,
    drivingDurationMinutes: 9,
    totalDurationMinutes: 19,
    isCovered: false,
    isBookable: true,
    hasEvCharging: false,
    isAccessible: true,
    isOpen24Hours: true,
    isOutsideZtl: true,
    maxVehicleHeightCm: 250,
    totalSpaces: 540,
    dataConfidence: 'high',
    dataSource: 'demo',
    lastVerifiedAt: '2026-07-11T08:00:00Z',
    tags: ['No ZTL', 'Prenotabile', 'H24', 'Accessibile'],
    isDemo: true,
  },
  {
    id: 'demo-porto',
    name: 'Parqo Porto',
    slug: 'parqo-porto',
    description: 'Parcheggio economico un po’ decentrato, adatto a soste lunghe.',
    address: 'Lungomare del Porto 22',
    city: 'Città Demo',
    ...offset(-1200, -900),
    pricePerHour: 1.2,
    dailyMaxPrice: 10,
    estimatedTotalPrice: 3.6,
    currency: 'EUR',
    walkingDistanceMeters: 1500,
    walkingDurationMinutes: 19,
    drivingDurationMinutes: 8,
    totalDurationMinutes: 27,
    isCovered: false,
    isBookable: false,
    hasEvCharging: false,
    isAccessible: false,
    isOpen24Hours: true,
    isOutsideZtl: true,
    maxVehicleHeightCm: 250,
    totalSpaces: 200,
    dataConfidence: 'medium',
    dataSource: 'demo',
    lastVerifiedAt: '2026-06-20T08:00:00Z',
    tags: ['No ZTL', 'Scoperto', 'H24'],
    isDemo: true,
  },
  {
    id: 'demo-verde',
    name: 'Parqo Verde',
    slug: 'parqo-verde',
    description: 'Parcheggio con colonnine di ricarica e accesso facile, fuori ZTL.',
    address: 'Viale dei Giardini 7',
    city: 'Città Demo',
    ...offset(-320, 260),
    pricePerHour: 2.5,
    dailyMaxPrice: 20,
    estimatedTotalPrice: 7.5,
    currency: 'EUR',
    walkingDistanceMeters: 420,
    walkingDurationMinutes: 6,
    drivingDurationMinutes: 10,
    totalDurationMinutes: 16,
    isCovered: false,
    isBookable: true,
    hasEvCharging: true,
    isAccessible: true,
    isOpen24Hours: false,
    openingTime: '06:00',
    closingTime: '23:00',
    isOutsideZtl: true,
    maxVehicleHeightCm: 230,
    totalSpaces: 150,
    dataConfidence: 'high',
    dataSource: 'demo',
    lastVerifiedAt: '2026-07-12T08:00:00Z',
    tags: ['No ZTL', 'EV', 'Prenotabile', 'Accessibile'],
    isDemo: true,
  },
  {
    id: 'demo-coperto',
    name: 'Parqo Coperto',
    slug: 'parqo-coperto',
    description: 'Autosilo coperto molto vicino, comodo ma con tariffa più alta.',
    address: 'Via Coperta 3',
    city: 'Città Demo',
    ...offset(90, -70),
    pricePerHour: 4.5,
    dailyMaxPrice: 35,
    estimatedTotalPrice: 13.5,
    currency: 'EUR',
    walkingDistanceMeters: 120,
    walkingDurationMinutes: 2,
    drivingDurationMinutes: 13,
    totalDurationMinutes: 15,
    isCovered: true,
    isBookable: true,
    hasEvCharging: false,
    isAccessible: true,
    isOpen24Hours: false,
    openingTime: '07:00',
    closingTime: '22:00',
    isOutsideZtl: false,
    maxVehicleHeightCm: 190,
    totalSpaces: 260,
    dataConfidence: 'high',
    dataSource: 'demo',
    lastVerifiedAt: '2026-07-09T08:00:00Z',
    tags: ['Coperto', 'Prenotabile', 'Accessibile', 'Altezza limitata'],
    isDemo: true,
  },
  {
    id: 'demo-express',
    name: 'Parqo Express',
    slug: 'parqo-express',
    description: 'Parcheggio rapido a raso, dati stimati e disponibilità variabile.',
    address: 'Via Rapida 15',
    city: 'Città Demo',
    ...offset(-260, -420),
    pricePerHour: 2.8,
    estimatedTotalPrice: 8.4,
    currency: 'EUR',
    walkingDistanceMeters: 560,
    walkingDurationMinutes: 8,
    drivingDurationMinutes: 7,
    totalDurationMinutes: 15,
    isCovered: false,
    isBookable: false,
    hasEvCharging: false,
    isAccessible: false,
    isOpen24Hours: true,
    isOutsideZtl: true,
    dataConfidence: 'low',
    dataSource: 'demo',
    lastVerifiedAt: '2026-05-02T08:00:00Z',
    tags: ['No ZTL', 'Scoperto', 'Dato stimato'],
    isDemo: true,
  },
  {
    id: 'demo-nord',
    name: 'Parqo Nord',
    slug: 'parqo-nord',
    description: 'Parcheggio coperto a nord, accesso semplice ma vicino alla ZTL.',
    address: 'Via del Nord 8',
    city: 'Città Demo',
    ...offset(520, 120),
    pricePerHour: 3,
    dailyMaxPrice: 24,
    estimatedTotalPrice: 9,
    currency: 'EUR',
    walkingDistanceMeters: 640,
    walkingDurationMinutes: 8,
    drivingDurationMinutes: 11,
    totalDurationMinutes: 19,
    isCovered: true,
    isBookable: false,
    hasEvCharging: true,
    isAccessible: true,
    isOpen24Hours: true,
    isOutsideZtl: false,
    maxVehicleHeightCm: 210,
    totalSpaces: 300,
    dataConfidence: 'medium',
    dataSource: 'demo',
    lastVerifiedAt: '2026-06-28T08:00:00Z',
    tags: ['Coperto', 'EV', 'H24', 'Accessibile'],
    isDemo: true,
  },
  {
    id: 'demo-basso',
    name: 'Parqo Basso',
    slug: 'parqo-basso',
    description: 'Autorimessa con soffitto basso: non adatta ai veicoli alti.',
    address: 'Vicolo Stretto 2',
    city: 'Città Demo',
    ...offset(160, 200),
    pricePerHour: 2.6,
    dailyMaxPrice: 22,
    estimatedTotalPrice: 7.8,
    currency: 'EUR',
    walkingDistanceMeters: 300,
    walkingDurationMinutes: 4,
    drivingDurationMinutes: 12,
    totalDurationMinutes: 16,
    isCovered: true,
    isBookable: true,
    hasEvCharging: false,
    isAccessible: false,
    isOpen24Hours: false,
    openingTime: '08:00',
    closingTime: '20:00',
    isOutsideZtl: false,
    maxVehicleHeightCm: 180,
    totalSpaces: 90,
    dataConfidence: 'medium',
    dataSource: 'demo',
    lastVerifiedAt: '2026-07-01T08:00:00Z',
    tags: ['Coperto', 'Prenotabile', 'Altezza limitata'],
    isDemo: true,
  },
  {
    id: 'demo-est',
    name: 'Parqo Est',
    slug: 'parqo-est',
    description: 'Parcheggio scoperto a est, buon compromesso tra prezzo e distanza.',
    address: 'Corso Est 40',
    city: 'Città Demo',
    ...offset(-140, 720),
    pricePerHour: 2.2,
    dailyMaxPrice: 18,
    estimatedTotalPrice: 6.6,
    currency: 'EUR',
    walkingDistanceMeters: 520,
    walkingDurationMinutes: 7,
    drivingDurationMinutes: 9,
    totalDurationMinutes: 16,
    isCovered: false,
    isBookable: true,
    hasEvCharging: false,
    isAccessible: true,
    isOpen24Hours: true,
    isOutsideZtl: true,
    maxVehicleHeightCm: 250,
    totalSpaces: 280,
    dataConfidence: 'high',
    dataSource: 'demo',
    lastVerifiedAt: '2026-07-13T08:00:00Z',
    tags: ['No ZTL', 'Scoperto', 'Prenotabile', 'H24', 'Accessibile'],
    isDemo: true,
  },
  {
    id: 'demo-ovest',
    name: 'Parqo Ovest',
    slug: 'parqo-ovest',
    description: 'Piccolo parcheggio a ovest con orario limitato e pochi posti.',
    address: 'Via Ovest 12',
    city: 'Città Demo',
    ...offset(220, -560),
    pricePerHour: 2,
    dailyMaxPrice: 15,
    estimatedTotalPrice: 6,
    currency: 'EUR',
    walkingDistanceMeters: 700,
    walkingDurationMinutes: 9,
    drivingDurationMinutes: 8,
    totalDurationMinutes: 17,
    isCovered: false,
    isBookable: false,
    hasEvCharging: false,
    isAccessible: false,
    isOpen24Hours: false,
    openingTime: '09:00',
    closingTime: '19:00',
    isOutsideZtl: true,
    maxVehicleHeightCm: 220,
    totalSpaces: 60,
    dataConfidence: 'low',
    dataSource: 'demo',
    lastVerifiedAt: '2026-04-18T08:00:00Z',
    tags: ['No ZTL', 'Scoperto', 'Dato stimato'],
    isDemo: true,
  },
  {
    id: 'demo-premium',
    name: 'Parqo Premium',
    slug: 'parqo-premium',
    description: 'Struttura coperta premium a due passi, servizi completi e ricarica.',
    address: 'Galleria Centrale 1',
    city: 'Città Demo',
    ...offset(70, 60),
    pricePerHour: 5,
    dailyMaxPrice: 40,
    estimatedTotalPrice: 15,
    currency: 'EUR',
    walkingDistanceMeters: 90,
    walkingDurationMinutes: 2,
    drivingDurationMinutes: 13,
    totalDurationMinutes: 15,
    isCovered: true,
    isBookable: true,
    hasEvCharging: true,
    isAccessible: true,
    isOpen24Hours: true,
    isOutsideZtl: false,
    maxVehicleHeightCm: 200,
    totalSpaces: 180,
    dataConfidence: 'high',
    dataSource: 'demo',
    lastVerifiedAt: '2026-07-13T08:00:00Z',
    tags: ['Coperto', 'Prenotabile', 'EV', 'Accessibile', 'H24'],
    isDemo: true,
  },
  {
    id: 'demo-sud',
    name: 'Parqo Sud',
    slug: 'parqo-sud',
    description: 'Parcheggio a raso a sud, capiente e adatto anche ai van.',
    address: 'Via del Sud 55',
    city: 'Città Demo',
    ...offset(-780, -320),
    pricePerHour: 1.8,
    dailyMaxPrice: 14,
    estimatedTotalPrice: 5.4,
    currency: 'EUR',
    walkingDistanceMeters: 950,
    walkingDurationMinutes: 12,
    drivingDurationMinutes: 8,
    totalDurationMinutes: 20,
    isCovered: false,
    isBookable: true,
    hasEvCharging: false,
    isAccessible: true,
    isOpen24Hours: true,
    isOutsideZtl: true,
    maxVehicleHeightCm: 320,
    totalSpaces: 420,
    dataConfidence: 'medium',
    dataSource: 'demo',
    lastVerifiedAt: '2026-07-05T08:00:00Z',
    tags: ['No ZTL', 'Scoperto', 'H24', 'Accessibile', 'Prenotabile'],
    isDemo: true,
  },
];
